### PR TITLE
Fix #23

### LINKED ISSUE #23: onResponse doesn´t called after adding TikXmlConverterFactory.create
Im doing the following to create the TikXml object
```java
TikXml tikXml = new TikXml.Builder()
                .exceptionOnUnreadXml(false)
                .build();
```

adding the converter factory

```java
...
.addConverterFactory(TikXmlConverterFactory.create(tikXml));
...
```

My object
```java
@Xml(name = "myroottag", scanMode = ScanMode.ANNOTATIONS_ONLY)
public class ResultData {

    @com.tickaroo.tikxml.annotation.Path("profile")
    @com.tickaroo.tikxml.annotation.Element(name = "user")
    private User mUser;

}

@Xml(scanMode = ScanMode.ANNOTATIONS_ONLY)
public class User extends RealmObject implements IIdentifyable {

    @PrimaryKey
    @PropertyElement(name = "id")
    private int mIdentifier;
}
```

### PR DESCRIPTION
**Pull request by FabianTerhorst**

### CODE REVIEW

File: core/src/test/java/com/tickaroo/tikxml/reading/JsonArrayReaderTest.java [hunk 1]
```diff
@@ -0,0 +1,45 @@
...
+
+    public static JsonElement readerFrom(String xml) throws IOException {
+        TikXml tikXml = new TikXml.Builder()
+                .addTypeAdapter(JsonElement.class, new JsonTypeAdapter())
+                .build();
+        Buffer buffer = new Buffer();
+        buffer.writeUtf8(xml);
+        return tikXml.read(buffer, JsonElement.class);
+    }
+}
```
Comment (sockeqwe) [inline core/src/test/java/com/tickaroo/tikxml/reading/JsonArrayReaderTest.java]: Imho: this should rather be part of [XmlReaderTest](https://github.com/Tickaroo/tikxml/blob/master/core/src/test/java/com/tickaroo/tikxml/XmlReaderTest.java) because I only want to test if the XmlReader is working properly with cdata + json arrays. 

So basically just test if the string retuned from `Assert.equals("[{a:'b'}, {b:'c'}]", reader.nextTextContent())`

just have a look at similar tests in `XmlReaderTest`

**Comment by sockeqwe** [comment]
Thanks, awesome work! I just have added a note regarding unit testing.

**Comment by FabianTerhorst** [comment]
i have updated the pr

**Comment by FabianTerhorst** [comment]
travis build finished.

File: core/src/main/java/com/tickaroo/tikxml/XmlReader.java [hunk 2]
```diff
@@ -617,7 +619,7 @@ public boolean nextTextContentAsBoolean() throws IOException {
   private long indexOfClosingCDATA() throws IOException {
     long index;
     do {
```
Comment (sockeqwe) [inline core/src/main/java/com/tickaroo/tikxml/XmlReader.java]: I think this loop is actually not needed anymore ...

Comment (sockeqwe) [inline core/src/main/java/com/tickaroo/tikxml/XmlReader.java]: Should be enough with:
```java
private long indexOfClosingCDATA() throws IOException {

  long index = source.indexOf(CDATA_CLOSE);
  if (index == -1) {
          throw new EOFException("<![CDATA[ at " + getPath() + " has never been closed with ]]>");
  }
  return index;
}
```

Comment (FabianTerhorst) [inline core/src/main/java/com/tickaroo/tikxml/XmlReader.java]: you are right, thanks.

Comment (FabianTerhorst) [inline core/src/main/java/com/tickaroo/tikxml/XmlReader.java]: i have updated the pr

**Comment by sockeqwe** [comment]
Thanks, a new snapshot `0.5.1-SNAPSHOT` will be deployed automatically
